# Generated by Django 5.1.2 on 2024-10-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descriptin', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=20)),
                ('gmail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('cv', models.FileField(upload_to='cv')),
                ('project_completed', models.IntegerField()),
            ],
        ),
    ]
