# Generated by Django 5.1.2 on 2024-10-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=200)),
                ('where', models.CharField(max_length=200)),
                ('about', models.TextField()),
            ],
        ),
    ]
